# Generated by Django 4.2.29 on 2026-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpagecontent_companyhighlight_contactpagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('section_badge', models.CharField(default='Personal Profile', max_length=50)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='portfolio/profile/')),
                ('introduction', models.TextField(blank=True, help_text='Short intro shown near your portfolio profile.')),
                ('experience_summary', models.TextField(blank=True, help_text='Write about your experience, strengths, and work style.')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills or specialties.', max_length=300)),
                ('primary_button_text', models.CharField(default='Contact Me', max_length=50)),
                ('secondary_button_text', models.CharField(default='View Services', max_length=50)),
            ],
            options={
                'verbose_name': 'Portfolio Profile',
                'verbose_name_plural': 'Portfolio Profile',
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
