# Generated by Django 4.2.29 on 2026-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolioprofile_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='map_embed_url',
            field=models.CharField(blank=True, help_text="Enter coordinates as 'latitude,longitude' e.g. '24.8607,67.0011'", max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='map_placeholder_text',
            field=models.CharField(default='Set map coordinates in admin panel.', max_length=150),
        ),
    ]
